# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
